### PR TITLE
Popup preview for Vim

### PR DESCRIPTION
**Pull request by Bakudankun**
Hello!
Now GitHub Copilot has been released a while ago, and I'm losing my access to it next month, I think it's about time to share my mod.

This mod is for Vim, to show Copilot suggestions just like in Neovim!

This is done by using two popup windows, the suggestion popup and the pseudo-split popup.

This behavior is automatically activated on Vim if `:Copilot split` is not used.

This PR is a bit big and hacky, so you may not want to merge this, and I think that's fine.
If you are willing to adopt this, feel free to apply in any way you like. It is **not** recommended to just press the merge button because this fork has so many commits (including "merge upstream" commits).

### CODE REVIEW

**Comment by tpope** [comment]
Vim just got support for virtual text, which means proper Copilot support for Vim should land soon. Unfortunately that means this popup implementation is about to be superseded.

**Comment by mattn** [comment]
Unfortunately, copilot.vim 1.5.0 hangs always on Windows. When goes to insert mode, node.exe takes high CPU load. This is output of `node agent.js`.

image

**Comment by tpope** [comment]
Are you sure that's the latest agent.js from the copilot.vim repo? That's an old bug that should be fixed.

**Comment by mattn** [comment]
The 1.4.0 agent.js is working, but the 1.5.0 makes heavy loop with errors. Sorry, I forgot to tell you that I am running agent.js on v18.4.0 with g:copilot_ignore_node_version.

**Comment by tpope** [comment]
Please try with Node 16.

**Pull request closed without merging**
